#!/bin/sh
### BEGIN INIT INFO
# Provides:             readkey
# Required-Start:       $networking
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    Raspebrry Pi Tape Remote (readkey)
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/readkey
NAME=readkey
DESC="Raspebrry Pi Tape Remote"

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        #start-stop-daemon -S -x "$DAEMON" -b
        $DAEMON &
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        #start-stop-daemon -K -n $NAME
        ps | grep "$DAEMON" | grep -v grep | awk '{print $1}' | xargs kill
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        #start-stop-daemon -K -n $NAME
        ps | grep "$DAEMON" | grep -v grep | awk '{print $1}' | xargs kill
        sleep 1
        #start-stop-daemon -S -x "$DAEMON" -b
        $DAEMON &
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
