#!/usr/bin/env python3
import evdev
import urllib
import sys
#from pprint import pprint as pp

devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]

flirc = '/dev/input/event0'
for dev in devices:
    if('flirc' in dev.name):
        flirc=dev.fn

dev = evdev.InputDevice(flirc)

for event in dev.read_loop():
    if(event.type == evdev.ecodes.EV_KEY and event.value == 1):
        key = evdev.ecodes.KEY[event.code]
        #pp(key)
        if(key == 'KEY_PLAYPAUSE'):
            urllib.request.urlopen("http://localhost:5000/play").read()

        #if(key == 'KEY_'):
        #    urllib.request.urlopen("http://localhost:5000/pause").read()

        if(key == 'KEY_STOPCD'):
            urllib.request.urlopen("http://localhost:5000/stop").read()

        if(key == 'KEY_FASTFORWARD'):
            urllib.request.urlopen("http://localhost:5000/fastforward").read()

        if(key == 'KEY_REWIND'):
            urllib.request.urlopen("http://localhost:5000/rewind").read()

        #if(key == 'KEY_'):
        #    urllib.request.urlopen("http://localhost:5000/record").read()
