#!/usr/bin/env python3
import logging
from flask import Flask
import RPi.GPIO as GPIO
import time
import sys
from pprint import pprint as pp

logging.basicConfig(level=logging.INFO,
                    format="%(levelname)s %(asctime)s %(message)s")

enable = 4
fastforward = 17
play = 18
rewind = 22
stop = 23
record = 24
pause = 25
on = GPIO.LOW
off = GPIO.HIGH

def init():
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(enable, GPIO.OUT)
    GPIO.output(enable, off)
    logging.info("sleeping" % cmd)
    time.sleep(0.2)
    GPIO.setup([fastforward, play, rewind, stop, record, pause], GPIO.OUT)
    logging.info("sleeping" % cmd)
    time.sleep(0.2)
    GPIO.output([fastforward, play, rewind, stop, record, pause], off)
    logging.info("sleeping" % cmd)
    time.sleep(0.2)
    GPIO.output(enable, on)

def clean():
    GPIO.output(enable, off)
    GPIO.cleanup()

def togglecmd(cmd):
    logging.info("got cmd: %s" % cmd)
    if(cmd == 'fastforward'):
        cmd = fastforward
    elif(cmd == 'play'):
        cmd = play
    elif(cmd == 'rewind'):
        cmd = rewind
    elif(cmd == 'stop'):
        cmd = stop
    elif(cmd == 'record'):
        cmd = record
    elif(cmd == 'pause'):
        cmd = pause
    else:
        logging.info("unknown cmd: %s" % cmd)
        return

    logging.info("sending cmd %s on" % cmd)
    GPIO.output(cmd, on)
    logging.info("sleeping" % cmd)
    time.sleep(0.2)
    logging.info("sending cmd %s off" % cmd)
    GPIO.output(cmd, off)

html='''
<p>
<a href=/play>play</a>
<a href=/pause>pause</a>
<a href=/stop>stop</a>
<a href=/fastforward>fastforward</a>
<a href=/rewind>rewind</a>
<a href=/record>record</a>
</p>
'''

app = Flask(__name__)
@app.route('/')
def help():
    return html

@app.route('/<cmd>')
def docmd(cmd):
    togglecmd(cmd)

    return '%s<br><p>cmd: %s</p>' % (html, cmd) 

if __name__ == '__main__':
    logging.info("initializing")
    init() 
    app.debug = True
    logging.info("listening")
    app.run(host='0.0.0.0')
    clean()

